###
POST  http://localhost:13000/auth/register/email
Content-Type: application/json

{
  "firstName": "User 2",
  "lastName": "Phan",
  "email": "user2@example.com",
  "password": "your-password"
}
###
###
POST  http://localhost:13000/auth/login/email
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "your-"
}
###